keys:
  - &dj 3157A0E73E7310AE7DD11A58E1A18DF6B4F919E4
  - &host_electron age1lycmmsnl6nnu4a4wxp56s888rn7nd6rf6ftjp07gj7qkwgv6c49smzdfhc

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *dj
      age:
      - *host_electron